### AWS Settings

# name of the AWS profile to use from ~/.aws/credentials
aws_profile: "ca-irakli-aws"

project_name: "MSA DEMO"
project_key: "msa_demo" # May NOT contain spaces!

key_name: ssh/private-key.pem
aws_instance_type: m3.medium
aws_image: ami-d05e75b8 # Ubuntu Server 14.04 LTS (HVM), SSD Volume Type
aws_security_group_web: "{{ project_key }}_web"
aws_security_group_consul: "{{ project_key }}_consul"
aws_ssh_key_name: "{{ project_name }} SSH Keys"
aws_region: "us-east-1"
aws_az: "us-east-1b"


# Feel free to edit "exact_count" numbers but editing anything else here may require
# corresponding changes in the code, which is not advisable. This is not a config file, per se.

server_clusters: 
  - zone: "{{ aws_az }}"
    exact_count: 3
    assign_public_ip: no
    tags:
      cluster: "{{ project_key }}"
      class: consul_servers
      subnet_tag: "{{ project_key }}_consul"
    groups:
      - "{{ aws_security_group_web }}"
      - "{{ aws_security_group_consul }}"

  - zone: "{{ aws_az }}"
    exact_count: 3
    assign_public_ip: yes
    tags:
      cluster: "{{ project_key }}"
      class: gateway_servers
      subnet_tag: "{{ project_key }}_web"
    groups:
          - "{{ aws_security_group_web }}"

  - zone: "{{ aws_az }}"
    exact_count: 3
    assign_public_ip: no
    tags:
      cluster: "{{ project_key }}"
      class: services_servers
      subnet_tag: "{{ project_key }}_web"
    groups:
          - "{{ aws_security_group_web }}"


#  - { class: 'gateway_servers', exact_count: 3, dict: { 'class' : 'gateways' } }
#  - { class: 'docker_servers', exact_count: 3, dict: { 'class' : 'dockers' } }

consul_servers: 
  # If you have public/private IPs (e.g. at EC2) you may want these to be 
  # the private IPs, but public ones may work too (depending on Firewall rules).
 # - 10.153.199.11
  #- 10.136.78.122
  #- 10.146.235.71

ansible_ssh_private_key_file: ssh/private-key.pem
ansible_ssh_user: ubuntu