### AWS Settings

# name of the AWS profile to use from ~/.aws/credentials
aws_profile: "ca-irakli-aws"

project_name: "MSA DEMO"
project_key: "msa_demo" # May NOT contain spaces!

key_name: ssh/private-key.pem
aws_instance_type: m3.medium
aws_image: ami-d05e75b8 # Ubuntu Server 14.04 LTS (HVM), SSD Volume Type

aws_security_group_web: "{{ project_key }}_web"
aws_security_group_consul: "{{ project_key }}_consul"
aws_security_group_services: "{{ project_key }}_microservices"
aws_security_group_db: "{{ project_key }}_db"
aws_security_group_cagateway: "{{ project_key }}_ca_gateway"

aws_ssh_key_name: "{{ project_name }} SSH Keys"
aws_region: "us-east-1"
aws_az: "us-east-1b"
aws_az_alt: "us-east-1c"

# This needs to be hardened once we set up VPN
aws_consul_security_cidr_ip: "0.0.0.0/0"
#aws_consul_security_cidr_ip: "10.0.0.0/16"

# microservices to install from DockerHub
# @see: roles/aws-server-creation/security-setup.yml -> {{ project_name }} Microservices Security Group
dockerhub_microservices:
  - "image" : "theapiacademy/shippinginc-customer-ms"
    "name"  : "shippinginc-customer-ms"
    "ports" : "3000"

  - "image" : "theapiacademy/shippinginc-shipments-ms"
    "name"  : "shippinginc-shipments-ms"
    "ports" : "3000"



# Feel free to edit "exact_count" numbers but editing anything else here may require
# corresponding changes in the code, which is not advisable. This is not a config file, per se.

server_clusters: 
  - zone: "{{ aws_az }}"
    exact_count: 3
    assign_public_ip: no
    tags:
      cluster: "{{ project_key }}"
      class: consul_servers
      subnet_tag: "{{ project_key }}_consul"
    groups:
      - "{{ aws_security_group_web }}"
      - "{{ aws_security_group_consul }}"

  - zone: "{{ aws_az }}"
    exact_count: 3
    assign_public_ip: yes
    tags:
      cluster: "{{ project_key }}"
      class: gateway_servers
      subnet_tag: "{{ project_key }}_web"
    groups:
          - "{{ aws_security_group_web }}"
          - "{{ aws_security_group_cagateway }}"

  - zone: "{{ aws_az }}"
    exact_count: 3
    assign_public_ip: no
    tags:
      cluster: "{{ project_key }}"
      class: services_servers
      subnet_tag: "{{ project_key }}_web"
    groups:
          - "{{ aws_security_group_web }}"
          - "{{ aws_security_group_services }}"

ansible_ssh_private_key_file: ssh/private-key.pem
ansible_ssh_user: ubuntu