---

  #- debug:
  #    msg: "{{ groups.tag_class_consul_servers | length }}"

  - name: Stop/Removes docker client agent containers if running (Idempotence)
    docker:
      image: "gliderlabs/consul-agent"
      state: absent

  - name: Launch Consul Client Agent Containers
    docker:
      name: consul-agent
      detach: true
      image: "gliderlabs/consul-agent"
      command: "-advertise {{inventory_hostname}} "
      state: restarted
      # restart_policy: "on-failure"
      ports:
        - 8300:8300
        - 8301:8301
        - 8301:8301/udp
        - 8302:8302
        - 8302:8302/udp
        - 8400:8400
        - 8500:8500
        - 53:53/udp

  - name: Make Consul agents join the cluster
    shell: "docker exec consul-agent consul join {{item}}"
    with_items: groups.tag_class_consul_servers