---

  # Docker container "restarting" is flaky. Remove and start is the bulletproof way

  - name: Stop/Removes docker server containers if running (Idempotence)
    docker:
      image: "gliderlabs/consul-server"
      state: absent

  - name: Launch Consul Server Containers
    docker:
      name: consul-server
      detach: true
      image: "gliderlabs/consul-server"
      command: "-server -advertise {{inventory_hostname}} -bootstrap-expect {{ groups.tag_class_consul_servers | length }}"
      state: started
      env:
        # http://gliderlabs.com/registrator/latest/user/services/#detecting-services
        # https://github.com/gliderlabs/registrator/issues/132
        SERVICE_IGNORE: always
      # restart_policy: "on-failure"
      ports:
        - 8300:8300
        - 8301:8301
        - 8301:8301/udp
        - 8302:8302
        - 8302:8302/udp
        - 8400:8400
        - 8500:8500
        - 53:8600
        - 53:8600/udp
        #- 53:53/udp

  - name: Make Consul servers join the cluster
    shell: "docker exec consul-server consul join {{item}}"
    with_items: groups.tag_class_consul_servers
    #when: item != "{{ groups.tag_class_consul_servers | first }}"