---

# http://docs.ansible.com/ansible/ec2_module.html#requirements

- name: Launch Server Clusters
  ec2:
     profile: "{{ aws_profile }}"
     key_name: "{{ aws_ssh_key_name }}"
     group: "{{ aws_security_group_consul }}"
     instance_type: "{{ aws_instance_type }}"
     image: "{{ aws_image }}"
     wait: true
     region: "{{ aws_region }}"
     vpc_subnet_id: "{{item[1]['id']}}"
     #assign_public_ip: yes
     instance_tags: "{{ item[0].tags }}"
     exact_count: "{{ item[0].exact_count }}"
     count_tag: "{{ item[0].tags }}"
     zone: "{{ item[0].zone }}"
  when: item[0]['tags']['subnet_tag'] == item[1]['resource_tags']['Tier']
  with_nested:
    - "{{server_clusters}}"
    - "{{ vpc_settings['subnets'] }}"
  register: ec2_consul_cluster

- name: created clusters
  debug: var=ec2_consul_cluster

#- name: Add new instance to host group
#  add_host: hostname={{ item.public_ip }} groupname=launched
#  with_items: ec2.instances

#- debug: msg="opa {{ ec2_consul_cluster }}"

#- name: Wait for SSH to come up
#  wait_for: host={{ item.public_dns_name }} port=22 delay=20 timeout=420 state=started
#  with_items:  ec2_consul_cluster.instances